package src.GameObjects;
public enum EnchantmentTypes {
    EXTRA_TIME_ENCHANTMENT,
    CLOAK_OF_PROTECTION_ENCHANTMENT,
    REVEAL_ENCHANTMENT,
    LURING_GEM_ENCHANTMENT,
    EXTRA_LIFE_ENCHANTMENT
}